[package]
name = "ex3_from_shinobu-x_1"
version = "0.1.0"
authors = ["toshihiro konda <kontoshi0317@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
